_type: llm_chain
llm:
  _type: openai
  best_of: 1
  frequency_penalty: 0
  logit_bias: {}
  max_tokens: 256
  model_name: text-davinci-003
  n: 1
  presence_penalty: 0
  request_timeout: null
  temperature: 0.7
  top_p: 1
memory: null
output_key: text
prompt:
  _type: few_shot
  example_prompt:
    _type: prompt
    input_variables:
    - text
    - label
    output_parser: null
    partial_variables: {}
    template: 'text: {text}

      label: {label}'
    template_format: f-string
    validate_template: true
  example_selector: null
  example_separator: '


    '
  examples:
  - label: positive
    text: That would be awesome!
  - label: negative
    text: This is awful!
  - label: neutral
    text: Today is hot day.
  input_variables:
  - input
  output_parser: null
  partial_variables: {}
  prefix: 'Classify the text into one of the following labels:

    - positive

    - negative

    - neutral

    '
  suffix: 'text: {input}'
  template_format: f-string
  validate_template: true
verbose: false
